//! CAS-R46-MODEL-SWITCH-OLD-THREAD-RECOVERY
//!
//! Local-only recovery for a Codex thread that became persistently unusable after a
//! model-switch / compaction boundary. The recovery path is deliberately conservative:
//! - preview is read-only;
//! - every mutation creates a rollout backup + SHA256 first;
//! - same-thread recovery rewinds at most ONE persisted turn per explicit click;
//! - workspace files are never reverted or edited;
//! - current Codex `thread/revert` is preferred; deprecated `thread/rollback` is used
//!   only when the bundled app-server explicitly reports method-not-found;
//! - a fork is offered as the non-destructive fallback.
//! No model inference request is generated by this module.

use axum::{
    extract::Query,
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use chrono::Local;
use codex_app_transfer_codex_integration::CodexPaths;
use codex_app_transfer_proxy::{proxy_log_dir, proxy_telemetry};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{
    fs::{self, File},
    io::{BufRead, BufReader, Read, Seek, SeekFrom, Write},
    path::{Path, PathBuf},
    process::{Child, ChildStdin, Command, Stdio},
    sync::mpsc::{self, Receiver},
    thread,
    time::{Duration, Instant, SystemTime},
};

use crate::admin::handlers::common::err;
use crate::admin::services::desktop::process;

const LOG_TAIL_BYTES: u64 = 8 * 1024 * 1024;
const RPC_TIMEOUT: Duration = Duration::from_secs(12);
const MAX_ROLLOUT_SCAN_DEPTH: usize = 5;
const MAX_CLI_SCAN_DEPTH: usize = 7;

#[derive(Debug, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryPreviewQuery {
    /// Optional exact Codex thread id. When omitted, r46 tries the newest structured
    /// upstream-error bundle in the local proxy log and extracts only metadata fields.
    thread_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Default)]
#[serde(rename_all = "camelCase")]
struct FailureEvidence {
    observed_at: Option<String>,
    raw_status: Option<u16>,
    model: Option<String>,
    request_kind: Option<String>,
    request_bytes: Option<u64>,
    turn_id: Option<String>,
    compaction_trigger: Option<String>,
    compaction_reason: Option<String>,
    source: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct RecoveryPreview {
    thread_id: String,
    thread_fingerprint: String,
    rollout_path: String,
    rollout_bytes: u64,
    rollout_sha256: String,
    evidence: FailureEvidence,
    codex_cli_found: bool,
    codex_cli_path: Option<String>,
    same_thread_recovery_supported: bool,
    safeguards: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryActionBody {
    thread_id: String,
    /// `rewindOne` preserves the same thread id and removes at most the newest
    /// persisted turn. `forkPrevious` creates a new thread through the prior boundary.
    action: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct BackupInfo {
    directory: String,
    rollout_copy: String,
    sha256: String,
    bytes: u64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct RecoveryActionResult {
    action: String,
    source_thread_id: String,
    resulting_thread_id: String,
    method: String,
    boundary_turn_id: Option<String>,
    visible_turns_before: usize,
    visible_turns_after: Option<usize>,
    backup: BackupInfo,
    codex_relaunched: bool,
    workspace_files_changed: bool,
    note: String,
}

#[derive(Debug, Clone)]
struct TurnWindow {
    newest: Option<String>,
    previous: Option<String>,
    visible_count: usize,
}

#[derive(Debug)]
struct RpcError {
    code: Option<i64>,
    message: String,
}

impl std::fmt::Display for RpcError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(code) = self.code {
            write!(f, "RPC {code}: {}", self.message)
        } else {
            f.write_str(&self.message)
        }
    }
}

impl RpcError {
    fn method_not_found(&self) -> bool {
        self.code == Some(-32601)
            || self
                .message
                .to_ascii_lowercase()
                .contains("method not found")
    }
}

struct AppServerRpc {
    child: Child,
    stdin: ChildStdin,
    rx: Receiver<String>,
    next_id: u64,
}

impl AppServerRpc {
    fn start(exe: &Path, codex_home: &Path) -> Result<Self, String> {
        let mut command = Command::new(exe);
        command
            .arg("app-server")
            .env("CODEX_HOME", codex_home)
            .env("RUST_LOG", "error")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::null());
        #[cfg(target_os = "windows")]
        {
            use std::os::windows::process::CommandExt;
            const CREATE_NO_WINDOW: u32 = 0x0800_0000;
            command.creation_flags(CREATE_NO_WINDOW);
        }

        let mut child = command
            .spawn()
            .map_err(|e| format!("启动 codex app-server 失败: {e}"))?;
        let stdin = child.stdin.take().ok_or("app-server stdin 不可用")?;
        let stdout = child.stdout.take().ok_or("app-server stdout 不可用")?;
        let (tx, rx) = mpsc::channel();
        thread::spawn(move || {
            let reader = BufReader::new(stdout);
            for line in reader.lines() {
                match line {
                    Ok(line) => {
                        if tx.send(line).is_err() {
                            break;
                        }
                    }
                    Err(_) => break,
                }
            }
        });

        let mut rpc = Self {
            child,
            stdin,
            rx,
            next_id: 1,
        };
        let _ = rpc.call(
            "initialize",
            json!({
                "clientInfo": {
                    "name": "codex_app_transfer_thread_recovery",
                    "title": "Codex App Transfer Thread Recovery",
                    "version": "r46"
                },
                "capabilities": { "experimentalApi": true }
            }),
        )?;
        rpc.notify("initialized", json!({}))?;
        Ok(rpc)
    }

    fn notify(&mut self, method: &str, params: Value) -> Result<(), String> {
        let line = serde_json::to_string(&json!({ "method": method, "params": params }))
            .map_err(|e| e.to_string())?;
        writeln!(self.stdin, "{line}").map_err(|e| format!("写 app-server stdin 失败: {e}"))?;
        self.stdin.flush().map_err(|e| e.to_string())
    }

    fn call(&mut self, method: &str, params: Value) -> Result<Value, RpcError> {
        let id = self.next_id;
        self.next_id = self.next_id.saturating_add(1);
        let line = serde_json::to_string(&json!({ "method": method, "id": id, "params": params }))
            .map_err(|e| RpcError {
                code: None,
                message: e.to_string(),
            })?;
        writeln!(self.stdin, "{line}").map_err(|e| RpcError {
            code: None,
            message: format!("写 app-server stdin 失败: {e}"),
        })?;
        self.stdin.flush().map_err(|e| RpcError {
            code: None,
            message: e.to_string(),
        })?;

        let deadline = Instant::now() + RPC_TIMEOUT;
        loop {
            let remaining = deadline.saturating_duration_since(Instant::now());
            if remaining.is_zero() {
                return Err(RpcError {
                    code: None,
                    message: format!("{method} 等待响应超时"),
                });
            }
            let raw = self.rx.recv_timeout(remaining).map_err(|_| RpcError {
                code: None,
                message: format!("{method} 未收到 app-server 响应"),
            })?;
            let Ok(message) = serde_json::from_str::<Value>(&raw) else {
                continue;
            };
            if message.get("id").and_then(Value::as_u64) != Some(id) {
                continue;
            }
            if let Some(error) = message.get("error") {
                return Err(RpcError {
                    code: error.get("code").and_then(Value::as_i64),
                    message: error
                        .get("message")
                        .and_then(Value::as_str)
                        .unwrap_or("unknown app-server error")
                        .to_owned(),
                });
            }
            return Ok(message.get("result").cloned().unwrap_or(Value::Null));
        }
    }
}

impl Drop for AppServerRpc {
    fn drop(&mut self) {
        let _ = self.stdin.flush();
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

pub async fn preview(Query(query): Query<RecoveryPreviewQuery>) -> impl IntoResponse {
    let evidence = latest_failure_evidence();
    let thread_id = query
        .thread_id
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
        .map(str::to_owned)
        .or_else(|| evidence.as_ref().map(|item| item.0.clone()));
    let Some(thread_id) = thread_id else {
        return err(
            StatusCode::NOT_FOUND,
            "没有从最近代理错误中识别到可恢复的 thread id；可手动输入完整 thread id",
        )
        .into_response();
    };
    if !safe_thread_id(&thread_id) {
        return err(StatusCode::BAD_REQUEST, "threadId 格式不安全").into_response();
    }
    let paths = match CodexPaths::from_home_env() {
        Ok(paths) => paths,
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    };
    let rollout = match find_rollout(&paths.codex_home, &thread_id) {
        Ok(Some(path)) => path,
        Ok(None) => {
            return err(
                StatusCode::NOT_FOUND,
                format!("未在 Codex sessions 中找到 thread {thread_id} 的 rollout"),
            )
            .into_response()
        }
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e).into_response(),
    };
    let metadata = match fs::metadata(&rollout) {
        Ok(value) => value,
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    };
    let sha256 = match sha256_file(&rollout) {
        Ok(value) => value,
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e).into_response(),
    };
    let cli = find_codex_cli();
    let evidence = evidence
        .filter(|item| item.0 == thread_id)
        .map(|item| item.1)
        .unwrap_or_else(|| FailureEvidence {
            source: "manual_thread_id".into(),
            ..Default::default()
        });
    let preview = RecoveryPreview {
        thread_fingerprint: fingerprint8(&thread_id),
        thread_id,
        rollout_path: rollout.display().to_string(),
        rollout_bytes: metadata.len(),
        rollout_sha256: sha256,
        evidence,
        codex_cli_found: cli.is_ok(),
        codex_cli_path: cli.ok().map(|p| p.display().to_string()),
        same_thread_recovery_supported: cfg!(target_os = "windows"),
        safeguards: vec![
            "执行修改前自动完整备份 rollout 并记录 SHA256".into(),
            "同 ID 恢复每次最多只回退 1 个 persisted turn".into(),
            "不会回滚、删除或修改 workspace 文件".into(),
            "优先 thread/revert；仅 method-not-found 时回退 thread/rollback(1)".into(),
            "恢复流程本身不发送任何模型推理请求".into(),
        ],
    };
    Json(json!({ "success": true, "preview": preview })).into_response()
}

pub async fn action(Json(body): Json<RecoveryActionBody>) -> impl IntoResponse {
    if !cfg!(target_os = "windows") {
        return err(StatusCode::NOT_IMPLEMENTED, "r46 旧会话恢复当前仅在 Windows 开放")
            .into_response();
    }
    let thread_id = body.thread_id.trim().to_owned();
    if !safe_thread_id(&thread_id) {
        return err(StatusCode::BAD_REQUEST, "threadId 格式不安全").into_response();
    }
    if !matches!(body.action.as_str(), "rewindOne" | "forkPrevious") {
        return err(StatusCode::BAD_REQUEST, "action 必须为 rewindOne 或 forkPrevious")
            .into_response();
    }

    let paths = match CodexPaths::from_home_env() {
        Ok(paths) => paths,
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e.to_string()).into_response(),
    };
    let rollout = match find_rollout(&paths.codex_home, &thread_id) {
        Ok(Some(path)) => path,
        Ok(None) => {
            return err(StatusCode::NOT_FOUND, "找不到目标 thread rollout").into_response()
        }
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e).into_response(),
    };
    let cli = match find_codex_cli() {
        Ok(path) => path,
        Err(e) => return err(StatusCode::INTERNAL_SERVER_ERROR, e).into_response(),
    };

    let action_name = body.action;
    let thread_for_work = thread_id.clone();
    let home_for_work = paths.codex_home.clone();
    let rollout_for_work = rollout.clone();
    let cli_for_work = cli.clone();
    let os = std::env::consts::OS;

    proxy_telemetry().logs.add(
        "WARN",
        format!(
            "[thread-recovery-r46] action={} stage=begin thread={} workspace_mutation=false",
            action_name,
            fingerprint8(&thread_id),
        ),
    );

    let outcome = tokio::task::spawn_blocking(move || {
        process::with_codex_closed(os, || {
            run_recovery_action(
                &home_for_work,
                &rollout_for_work,
                &cli_for_work,
                &thread_for_work,
                &action_name,
            )
        })
    })
    .await;

    let (inner, relaunched) = match outcome {
        Ok(Ok(value)) => value,
        Ok(Err(e)) => {
            return err(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("无法进入 Codex 安全维护窗口，未执行恢复: {e}"),
            )
            .into_response()
        }
        Err(e) => {
            return err(
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("恢复任务 join 失败: {e}"),
            )
            .into_response()
        }
    };

    let mut result = match inner {
        Ok(value) => value,
        Err(e) => {
            return err(StatusCode::INTERNAL_SERVER_ERROR, e).into_response();
        }
    };
    result.codex_relaunched = relaunched;

    proxy_telemetry().logs.add(
        "INFO",
        format!(
            "[thread-recovery-r46] action={} stage=complete source_thread={} resulting_thread={} method={} turns_before={} turns_after={} codex_relaunched={} workspace_mutation=false",
            result.action,
            fingerprint8(&result.source_thread_id),
            fingerprint8(&result.resulting_thread_id),
            result.method,
            result.visible_turns_before,
            result.visible_turns_after.map(|v| v.to_string()).unwrap_or_else(|| "unknown".into()),
            result.codex_relaunched,
        ),
    );

    Json(json!({ "success": true, "recovery": result })).into_response()
}

fn run_recovery_action(
    codex_home: &Path,
    rollout: &Path,
    cli: &Path,
    thread_id: &str,
    action: &str,
) -> Result<RecoveryActionResult, String> {
    // Backup is created *inside* the maintenance window and before app-server starts,
    // so the source rollout cannot change underneath the copy.
    let backup = backup_rollout(rollout, thread_id)?;
    let mut rpc = AppServerRpc::start(cli, codex_home)?;
    let before = latest_turn_window(&mut rpc, thread_id)?;

    match action {
        "rewindOne" => {
            let boundary = before
                .newest
                .clone()
                .ok_or("thread 没有可回退的 persisted turn")?;
            let method = match rpc.call(
                "thread/revert",
                json!({ "threadId": thread_id, "beforeTurnId": boundary }),
            ) {
                Ok(_) => "thread/revert".to_owned(),
                Err(error) if error.method_not_found() => {
                    rpc.call(
                        "thread/rollback",
                        json!({ "threadId": thread_id, "numTurns": 1 }),
                    )
                    .map_err(|e| format!("thread/revert 不受支持，thread/rollback(1) 也失败: {e}"))?;
                    "thread/rollback(1)".to_owned()
                }
                Err(error) => {
                    return Err(format!(
                        "thread/revert 返回非 method-not-found 错误，为避免误删未自动 fallback: {error}"
                    ))
                }
            };
            let after = latest_turn_window(&mut rpc, thread_id).ok();
            Ok(RecoveryActionResult {
                action: action.into(),
                source_thread_id: thread_id.into(),
                resulting_thread_id: thread_id.into(),
                method,
                boundary_turn_id: Some(boundary),
                visible_turns_before: before.visible_count,
                visible_turns_after: after.map(|v| v.visible_count),
                backup,
                codex_relaunched: false,
                workspace_files_changed: false,
                note: "已保持同一个 thread id，仅回退最新 1 个 persisted turn；请先在原会话发送一条很短的普通消息验证，不要立刻再次切模型或 compact。".into(),
            })
        }
        "forkPrevious" => {
            let boundary = before
                .previous
                .clone()
                .or_else(|| before.newest.clone())
                .ok_or("thread 没有可用于 fork 的 persisted turn")?;
            let result = match rpc.call(
                "thread/fork",
                json!({
                    "threadId": thread_id,
                    "lastTurnId": boundary,
                    "excludeTurns": true
                }),
            ) {
                Ok(value) => value,
                Err(error) => {
                    // Older app-server builds may not understand excludeTurns. Retrying the
                    // same non-destructive fork without it is safe; never retry mutation APIs.
                    if error.message.contains("excludeTurns") || error.message.contains("unknown field") {
                        rpc.call(
                            "thread/fork",
                            json!({ "threadId": thread_id, "lastTurnId": boundary }),
                        )
                        .map_err(|e| format!("thread/fork 失败: {e}"))?
                    } else {
                        return Err(format!("thread/fork 失败: {error}"));
                    }
                }
            };
            let new_id = result
                .get("thread")
                .and_then(|v| v.get("id"))
                .and_then(Value::as_str)
                .ok_or("thread/fork 成功响应缺少 result.thread.id")?
                .to_owned();
            Ok(RecoveryActionResult {
                action: action.into(),
                source_thread_id: thread_id.into(),
                resulting_thread_id: new_id,
                method: "thread/fork".into(),
                boundary_turn_id: Some(boundary),
                visible_turns_before: before.visible_count,
                visible_turns_after: None,
                backup,
                codex_relaunched: false,
                workspace_files_changed: false,
                note: "原 thread 未修改；已创建一个截止到前一安全边界的恢复副本。".into(),
            })
        }
        _ => Err("unsupported recovery action".into()),
    }
}

fn latest_turn_window(rpc: &mut AppServerRpc, thread_id: &str) -> Result<TurnWindow, String> {
    match rpc.call(
        "thread/turns/list",
        json!({
            "threadId": thread_id,
            "limit": 64,
            "sortDirection": "desc",
            "itemsView": "summary"
        }),
    ) {
        Ok(result) => {
            let ids = result
                .get("data")
                .and_then(Value::as_array)
                .map(|items| {
                    items
                        .iter()
                        .filter_map(|item| item.get("id").and_then(Value::as_str).map(str::to_owned))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            return Ok(TurnWindow {
                newest: ids.first().cloned(),
                previous: ids.get(1).cloned(),
                visible_count: ids.len(),
            });
        }
        Err(error) if error.method_not_found() => {}
        Err(error) => return Err(format!("thread/turns/list 失败: {error}")),
    }

    let result = rpc
        .call(
            "thread/read",
            json!({ "threadId": thread_id, "includeTurns": true }),
        )
        .map_err(|e| format!("thread/read fallback 失败: {e}"))?;
    let mut ids = result
        .get("thread")
        .and_then(|v| v.get("turns"))
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.get("id").and_then(Value::as_str).map(str::to_owned))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    ids.reverse();
    Ok(TurnWindow {
        newest: ids.first().cloned(),
        previous: ids.get(1).cloned(),
        visible_count: ids.len(),
    })
}

fn safe_thread_id(value: &str) -> bool {
    let value = value.trim();
    (16..=80).contains(&value.len())
        && value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}

fn fingerprint8(value: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{:08x}", (hash ^ (hash >> 32)) as u32)
}

fn sha256_file(path: &Path) -> Result<String, String> {
    let mut file = File::open(path).map_err(|e| format!("读取 rollout 失败: {e}"))?;
    let mut digest = Sha256::new();
    let mut buf = [0u8; 128 * 1024];
    loop {
        let n = file.read(&mut buf).map_err(|e| e.to_string())?;
        if n == 0 {
            break;
        }
        digest.update(&buf[..n]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

fn backup_rollout(source: &Path, thread_id: &str) -> Result<BackupInfo, String> {
    let root = codex_app_transfer_registry::config_dir()
        .ok_or("无法解析 codex-app-transfer config dir")?
        .join("thread-recovery");
    let stamp = Local::now().format("%Y%m%d-%H%M%S").to_string();
    let directory = root.join(format!("{stamp}-{}", fingerprint8(thread_id)));
    let backup_dir = directory.join("source-backup");
    fs::create_dir_all(&backup_dir).map_err(|e| format!("创建恢复备份目录失败: {e}"))?;
    let name = source
        .file_name()
        .ok_or("rollout 文件名不可用")?;
    let destination = backup_dir.join(name);
    fs::copy(source, &destination).map_err(|e| format!("备份 rollout 失败: {e}"))?;
    let bytes = fs::metadata(&destination).map_err(|e| e.to_string())?.len();
    let sha256 = sha256_file(&destination)?;
    let manifest = json!({
        "version": 1,
        "createdAt": Local::now().to_rfc3339(),
        "threadFingerprint": fingerprint8(thread_id),
        "sourcePath": source.display().to_string(),
        "backupPath": destination.display().to_string(),
        "bytes": bytes,
        "sha256": sha256,
        "workspaceFilesChanged": false,
        "note": "Conversation-history backup only; workspace files are intentionally untouched."
    });
    fs::write(
        directory.join("RECOVERY-BACKUP.json"),
        serde_json::to_vec_pretty(&manifest).map_err(|e| e.to_string())?,
    )
    .map_err(|e| format!("写恢复 manifest 失败: {e}"))?;
    Ok(BackupInfo {
        directory: directory.display().to_string(),
        rollout_copy: destination.display().to_string(),
        sha256,
        bytes,
    })
}

fn find_rollout(codex_home: &Path, thread_id: &str) -> Result<Option<PathBuf>, String> {
    let sessions = codex_home.join("sessions");
    if !sessions.is_dir() {
        return Err(format!("Codex sessions 目录不存在: {}", sessions.display()));
    }
    let mut matches = Vec::new();
    collect_named_files(&sessions, thread_id, 0, MAX_ROLLOUT_SCAN_DEPTH, &mut matches)?;
    matches.sort_by_key(|path| {
        fs::metadata(path)
            .and_then(|m| m.modified())
            .unwrap_or(SystemTime::UNIX_EPOCH)
    });
    Ok(matches.pop())
}

fn collect_named_files(
    dir: &Path,
    needle: &str,
    depth: usize,
    max_depth: usize,
    output: &mut Vec<PathBuf>,
) -> Result<(), String> {
    if depth > max_depth {
        return Ok(());
    }
    let entries = fs::read_dir(dir).map_err(|e| format!("读取 {} 失败: {e}", dir.display()))?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_named_files(&path, needle, depth + 1, max_depth, output)?;
        } else if path
            .file_name()
            .and_then(|v| v.to_str())
            .is_some_and(|name| name.contains(needle) && name.ends_with(".jsonl"))
        {
            output.push(path);
        }
    }
    Ok(())
}

fn find_codex_cli() -> Result<PathBuf, String> {
    for key in ["CODEX_CLI_PATH", "CODEX_BIN"] {
        if let Ok(value) = std::env::var(key) {
            let path = PathBuf::from(value.trim());
            if path.is_file() {
                return Ok(path);
            }
        }
    }

    #[cfg(target_os = "windows")]
    {
        // When Desktop is currently running this is the most exact source: use the
        // actual packaged runtime path instead of guessing a client version directory.
        if let Ok(output) = Command::new("powershell")
            .args([
                "-NoProfile",
                "-Command",
                "$p=Get-CimInstance Win32_Process -Filter \"Name='codex.exe'\" | Select-Object -First 1 -ExpandProperty ExecutablePath; if($p){$p}",
            ])
            .output()
        {
            if output.status.success() {
                let path = PathBuf::from(String::from_utf8_lossy(&output.stdout).trim());
                if path.is_file() {
                    return Ok(path);
                }
            }
        }

        if let Ok(output) = Command::new("where.exe").arg("codex.exe").output() {
            if output.status.success() {
                for line in String::from_utf8_lossy(&output.stdout).lines() {
                    let path = PathBuf::from(line.trim());
                    if path.is_file() {
                        return Ok(path);
                    }
                }
            }
        }

        if let Ok(local) = std::env::var("LOCALAPPDATA") {
            for root in [
                PathBuf::from(&local).join("OpenAI").join("Codex").join("runtimes"),
                PathBuf::from(&local).join("OpenAI").join("ChatGPT").join("runtimes"),
            ] {
                let mut hits = Vec::new();
                collect_codex_exes(&root, 0, MAX_CLI_SCAN_DEPTH, &mut hits);
                hits.sort_by_key(|path| {
                    fs::metadata(path)
                        .and_then(|m| m.modified())
                        .unwrap_or(SystemTime::UNIX_EPOCH)
                });
                if let Some(path) = hits.pop() {
                    return Ok(path);
                }
            }
        }
    }

    Err("未找到 Codex CLI/app-server 可执行文件；请先启动一次 Codex Desktop 后重试".into())
}

fn collect_codex_exes(dir: &Path, depth: usize, max_depth: usize, output: &mut Vec<PathBuf>) {
    if depth > max_depth || !dir.is_dir() {
        return;
    }
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_codex_exes(&path, depth + 1, max_depth, output);
        } else if path
            .file_name()
            .and_then(|v| v.to_str())
            .is_some_and(|name| name.eq_ignore_ascii_case("codex.exe"))
        {
            output.push(path);
        }
    }
}

fn latest_failure_evidence() -> Option<(String, FailureEvidence)> {
    let dir = proxy_log_dir()?;
    let mut files = fs::read_dir(dir)
        .ok()?
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| {
            path.file_name()
                .and_then(|v| v.to_str())
                .is_some_and(|name| name.starts_with("proxy-") && name.ends_with(".log"))
        })
        .collect::<Vec<_>>();
    files.sort_by_key(|path| {
        fs::metadata(path)
            .and_then(|m| m.modified())
            .unwrap_or(SystemTime::UNIX_EPOCH)
    });
    for path in files.into_iter().rev().take(3) {
        let Ok(tail) = read_tail(&path, LOG_TAIL_BYTES) else {
            continue;
        };
        if let Some(found) = parse_latest_failure(&tail) {
            return Some(found);
        }
    }
    None
}

fn read_tail(path: &Path, max_bytes: u64) -> Result<String, String> {
    let mut file = File::open(path).map_err(|e| e.to_string())?;
    let len = file.metadata().map_err(|e| e.to_string())?.len();
    let take = len.min(max_bytes);
    file.seek(SeekFrom::Start(len.saturating_sub(take)))
        .map_err(|e| e.to_string())?;
    let mut bytes = Vec::with_capacity(take as usize);
    file.read_to_end(&mut bytes).map_err(|e| e.to_string())?;
    Ok(String::from_utf8_lossy(&bytes).into_owned())
}

fn parse_latest_failure(text: &str) -> Option<(String, FailureEvidence)> {
    let mut end = text.len();
    for _ in 0..32 {
        let pos = text[..end].rfind("upstream error diag ")?;
        let after = &text[pos..text.len().min(pos + 40 * 1024)];
        let before = &text[pos.saturating_sub(8 * 1024)..pos];
        let thread_id = extract_json_string(after, "thread_id");
        if let Some(thread_id) = thread_id.filter(|id| safe_thread_id(id)) {
            let status = after
                .strip_prefix("upstream error diag ")
                .and_then(|rest| rest.split_whitespace().next())
                .and_then(|v| v.parse::<u16>().ok());
            let request_bytes = after
                .find("request body: <redacted> (")
                .and_then(|idx| {
                    let rest = &after[idx + "request body: <redacted> (".len()..];
                    rest.split_whitespace().next()?.parse::<u64>().ok()
                });
            let evidence = FailureEvidence {
                observed_at: line_timestamp(before),
                raw_status: status,
                model: last_model_line(before),
                request_kind: extract_json_string(after, "request_kind"),
                request_bytes,
                turn_id: extract_json_string(after, "turn_id"),
                compaction_trigger: extract_json_string(after, "trigger"),
                compaction_reason: extract_json_string(after, "reason"),
                source: "recent_proxy_upstream_error".into(),
            };
            return Some((thread_id, evidence));
        }
        end = pos;
    }
    None
}

fn extract_json_string(text: &str, key: &str) -> Option<String> {
    let marker = format!("\"{key}\":\"");
    let start = text.find(&marker)? + marker.len();
    let rest = &text[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_owned())
}

fn line_timestamp(before: &str) -> Option<String> {
    before
        .lines()
        .rev()
        .find(|line| line.contains("\tERROR\t") || line.contains("\tINFO\t"))
        .and_then(|line| line.split('\t').next())
        .map(str::to_owned)
}

fn last_model_line(before: &str) -> Option<String> {
    let line = before.lines().rev().find(|line| line.contains("\tINFO\tmodel: "))?;
    let value = line.split("model: ").nth(1)?.trim();
    Some(
        value
            .split('→')
            .next_back()
            .unwrap_or(value)
            .trim()
            .to_owned(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn r46_failure_parser_extracts_only_structural_metadata() {
        let sample = concat!(
            "2026-08-29 16:21:32\tINFO\tmodel: gpt-5.6-terra → gpt-5.6-terra\n",
            "2026-08-29 16:21:39\tERROR\tupstream error diag 400 http://localhost:8113/v1/responses\\\n",
            "  → outbound headers: [x-codex-turn-metadata={\"thread_id\":\"01a02a57-7180-7822-8c54-e3ed317a934e\",\"turn_id\":\"01a04e1c-33d9-7e03-a71a-e41e477d5782\",\"request_kind\":\"compaction\",\"compaction\":{\"trigger\":\"manual\",\"reason\":\"user_requested\"}}]\\\n",
            "  → request body: <redacted> (13941448 bytes)\\\n"
        );
        let (thread, evidence) = parse_latest_failure(sample).unwrap();
        assert_eq!(thread, "01a02a57-7180-7822-8c54-e3ed317a934e");
        assert_eq!(evidence.raw_status, Some(400));
        assert_eq!(evidence.model.as_deref(), Some("gpt-5.6-terra"));
        assert_eq!(evidence.request_kind.as_deref(), Some("compaction"));
        assert_eq!(evidence.request_bytes, Some(13_941_448));
        assert_eq!(evidence.compaction_trigger.as_deref(), Some("manual"));
        assert_eq!(evidence.compaction_reason.as_deref(), Some("user_requested"));
    }

    #[test]
    fn r46_thread_id_guard_rejects_paths() {
        assert!(safe_thread_id("01a02a57-7180-7822-8c54-e3ed317a934e"));
        assert!(!safe_thread_id("../../sessions/secret"));
        assert!(!safe_thread_id("C:\\Users\\x\\secret"));
    }

    #[test]
    fn r46_fingerprint_does_not_echo_thread_id() {
        let raw = "01a02a57-7180-7822-8c54-e3ed317a934e";
        let fp = fingerprint8(raw);
        assert_eq!(fp.len(), 8);
        assert_ne!(fp, raw);
    }
}
