<script setup lang="ts">
// 路由(转发)页 — 复刻原版布局(Image #8):① 状态条(运行态 + 端口 + 启停)
// ② 四列统计(总请求/成功/失败/今日) ③ 暗色日志面板(标题行 + 分列 time/level/message)。
import { computed, onMounted, onUnmounted, ref, watch, nextTick } from 'vue'
import { useProxyStore } from '@/stores/proxy'
import { getDroppedTools, type DroppedToolsStatus } from '@/api/system'
import { t } from '@/i18n'
import { useToast } from '@/composables/useToast'
import AppSwitch from '@/components/ui/AppSwitch.vue'
// CAS-R33-CHAIN-HEALTH
// CAS-R36-SAFE-RECOVERY
// CAS-R37-FAULT-ATTRIBUTION-QUOTA-GUARD
// CAS-R34-RUNTIME-BEHAVIOR-HEALTH
import {
  getChainHealth,
  recoverChainHealth,
  type ChainHealthSnapshot,
  type ChainHealthStatus,
  type ChainRecoveryReport,
} from '@/api/chainHealth'
import IconPlay from '~icons/lucide/play'
import IconSquare from '~icons/lucide/square'
import IconList from '~icons/lucide/list'
import IconCheck from '~icons/lucide/circle-check'
import IconX from '~icons/lucide/circle-x'
import IconCalendar from '~icons/lucide/calendar-days'
import IconFolder from '~icons/lucide/folder-open'
import IconTrash from '~icons/lucide/trash-2'
import IconRefreshCw from '~icons/lucide/refresh-cw'
import IconChevronDown from '~icons/lucide/chevron-down'
import IconWrench from '~icons/lucide/wrench'

const store = useProxyStore()
const { show: toast } = useToast()
let timer: number | undefined
let chainTimer: number | undefined

const portInput = ref<number>(18080)
const autoScroll = ref(true)
const logsEl = ref<HTMLElement>()

// CAS-R33-CHAIN-HEALTH
const chainHealth = ref<ChainHealthSnapshot | null>(null)
const chainLoading = ref(false)
const chainExpanded = ref(false)
const chainRecovering = ref(false)
const chainRecovery = ref<ChainRecoveryReport | null>(null)
const chainLayers = computed(() => {
  const h = chainHealth.value
  if (!h) return []
  return [
    { key: 'codex', label: t('chainHealth.layer.codex'), data: h.codex },
    { key: 'session', label: t('chainHealth.layer.session'), data: h.session },
    { key: 'mcp', label: t('chainHealth.layer.mcp'), data: h.mcp },
    { key: 'transfer', label: t('chainHealth.layer.transfer'), data: h.transfer },
    { key: 'gateway', label: t('chainHealth.layer.gateway'), data: h.gateway },
    { key: 'runtime', label: t('chainHealth.layer.runtime'), data: h.runtime.layer },
    { key: 'account', label: t('chainHealth.layer.account'), data: h.account },
    { key: 'upstream', label: t('chainHealth.layer.upstream'), data: h.upstream },
  ]
})
function chainStatusLabel(status: ChainHealthStatus) {
  return t(`chainHealth.status.${status}`)
}
async function loadChainHealth(force = false) {
  if (chainLoading.value) return
  chainLoading.value = true
  try {
    chainHealth.value = await getChainHealth(force)
  } catch (e) {
    if (force) toast((e as Error).message || t('chainHealth.loadFailed'), 'error')
  } finally {
    chainLoading.value = false
  }
}

// CAS-R36-SAFE-RECOVERY: only runs after an explicit click. No model inference
// request is generated by the recovery path.
async function onRecoverChain() {
  if (chainRecovering.value) return
  chainRecovering.value = true
  try {
    const result = await recoverChainHealth()
    chainRecovery.value = result.recovery
    chainHealth.value = result.health
    toast(t('chainHealth.recoveryComplete'), 'info')
  } catch (e) {
    toast((e as Error).message || t('chainHealth.recoveryFailed'), 'error')
  } finally {
    chainRecovering.value = false
  }
}

// [MOC-261 一-11] 静默丢弃工具诊断(金丝雀):本进程累计被丢弃的未知 Responses API 工具类型。
const dropped = ref<DroppedToolsStatus>({ total: 0, by_type: {} })
const droppedExpanded = ref(false)
const droppedEntries = computed(() =>
  Object.entries(dropped.value.by_type).sort((a, b) => b[1] - a[1]),
)
async function loadDropped() {
  try {
    dropped.value = await getDroppedTools()
  } catch {
    /* 诊断信息,失败忽略 */
  }
}

onMounted(async () => {
  await store.loadStatus().catch(() => {})
  portInput.value = store.port || 18080
  await store.loadLogs().catch(() => {})
  loadDropped()
  loadChainHealth()
  scrollToBottom()
  timer = window.setInterval(() => {
    if (store.running) {
      store.loadLogs().catch(() => {})
      loadDropped()
    }
  }, 2000)
  chainTimer = window.setInterval(() => loadChainHealth(), 10000)
})
onUnmounted(() => {
  if (timer) clearInterval(timer)
  if (chainTimer) clearInterval(chainTimer)
})

// 端口随后端状态同步(用户编辑后下一次 loadStatus 会覆盖,符合原版行为)
watch(
  () => store.port,
  (p) => {
    if (p) portInput.value = p
  },
)
watch(
  () => store.logs.length,
  () => {
    if (autoScroll.value) scrollToBottom()
  },
)
function scrollToBottom() {
  nextTick(() => {
    if (logsEl.value) logsEl.value.scrollTop = logsEl.value.scrollHeight
  })
}

async function onToggle() {
  const turnOn = !store.running
  try {
    await store.toggle(turnOn, turnOn ? portInput.value : undefined)
  } catch (e) {
    toast((e as Error).message || '操作失败', 'error')
  }
  store.loadLogs().catch(() => {})
}
async function onViewLogs() {
  try {
    await store.openLogDir()
  } catch (e) {
    toast((e as Error).message || '打开失败', 'error')
  }
}
async function onClearLogs() {
  try {
    await store.clearLogs()
  } catch (e) {
    toast((e as Error).message || '清除失败', 'error')
  }
}
</script>

<template>
  <div class="proxy">
    <!-- ① 状态条 -->
    <div class="status-card">
      <div class="status-card__left">
        <span class="pulse" :class="{ 'pulse--on': store.running }" />
        <span class="status-text" :class="{ 'status-text--on': store.running }">
          {{ store.running ? t('status.running') : t('status.stopped') }}
        </span>
        <span class="status-sub">{{ store.hybridDirectMode ? t('proxy.hybridDirectGateway') : t('proxy.localhost') }}</span>
      </div>
      <div class="status-card__right">
        <label class="port-field">
          <span class="port-label">{{ t('proxy.port') }}</span>
          <input v-model.number="portInput" type="number" class="port-input" min="1" max="65535" />
        </label>
        <button class="proxy-toggle" :class="store.running ? 'is-stop' : 'is-start'" @click="onToggle">
          <component :is="store.running ? IconSquare : IconPlay" class="proxy-toggle__icon" />
          <span>{{ store.running ? t('proxy.stop') : t('proxy.start') }}</span>
        </button>
      </div>
    </div>

    <!-- ② 四列统计(单行:图标-数值-文字, 高度与状态条一致) -->
    <div class="stat-grid">
      <div class="stat-card">
        <span class="stat-card__icon"><IconList /></span>
        <strong class="stat-card__value">{{ store.stats.total }}</strong>
        <span class="stat-card__label">{{ t('proxy.stats.total') }}</span>
      </div>
      <div class="stat-card">
        <span class="stat-card__icon stat-card__icon--ok"><IconCheck /></span>
        <strong class="stat-card__value">{{ store.stats.success }}</strong>
        <span class="stat-card__label">{{ t('proxy.stats.success') }}</span>
      </div>
      <div class="stat-card">
        <span class="stat-card__icon stat-card__icon--err"><IconX /></span>
        <strong class="stat-card__value">{{ store.stats.failed }}</strong>
        <span class="stat-card__label">{{ t('proxy.stats.failed') }}</span>
      </div>
      <div class="stat-card">
        <span class="stat-card__icon"><IconCalendar /></span>
        <strong class="stat-card__value">{{ store.stats.today }}</strong>
        <span class="stat-card__label">{{ t('proxy.stats.today') }}</span>
      </div>
    </div>


    <!-- CAS-R33-CHAIN-HEALTH -->
    <section class="chain-health" :class="chainHealth ? `chain-health--${chainHealth.overall}` : ''">
      <div class="chain-health__head">
        <div>
          <div class="chain-health__title-row">
            <span class="chain-health__pulse" />
            <h2>{{ t('chainHealth.title') }}</h2>
            <span v-if="chainHealth" class="chain-health__overall">
              {{ chainStatusLabel(chainHealth.overall) }}
            </span>
          </div>
          <p class="chain-health__summary">
            {{ chainHealth?.overallSummary || t('chainHealth.loading') }}
          </p>
          <p v-if="chainHealth?.provider" class="chain-health__provider">
            {{ chainHealth.provider.name }} · {{ chainHealth.provider.displayUrl }}
          </p>
          <p v-if="chainHealth?.diagnosis" class="chain-health__provider">
            {{ t('chainHealth.attribution') }}：{{ chainHealth.diagnosis.summary }}
          </p>
        </div>
        <div class="chain-health__actions">
          <button
            class="chain-health__button chain-health__button--repair"
            :disabled="chainRecovering"
            @click="onRecoverChain"
          >
            <IconWrench :class="{ 'is-spinning': chainRecovering }" />
            {{ t('chainHealth.recover') }}
          </button>
          <button class="chain-health__button" :disabled="chainLoading" @click="loadChainHealth(true)">
            <IconRefreshCw :class="{ 'is-spinning': chainLoading }" />
            {{ t('chainHealth.refresh') }}
          </button>
          <button class="chain-health__button" @click="chainExpanded = !chainExpanded">
            <IconChevronDown :class="{ 'is-open': chainExpanded }" />
            {{ t('chainHealth.details') }}
          </button>
        </div>
      </div>

      <div class="chain-health__grid">
        <article
          v-for="layer in chainLayers"
          :key="layer.key"
          class="chain-layer"
          :class="`chain-layer--${layer.data.status}`"
        >
          <div class="chain-layer__head">
            <span class="chain-layer__dot" />
            <strong>{{ layer.label }}</strong>
            <span>{{ chainStatusLabel(layer.data.status) }}</span>
          </div>
          <p>{{ layer.data.summary }}</p>
          <small v-if="layer.data.latencyMs != null">{{ layer.data.latencyMs }} ms</small>
        </article>
      </div>

      <div v-if="chainRecovery" class="chain-health__recovery-report">
        <strong>{{ t('chainHealth.recoveryReport') }}</strong>
        <span>{{ chainRecovery.classification }}</span>
        <ul>
          <li v-for="action in chainRecovery.actions" :key="`${action.action}-${action.detail}`">
            <code>{{ action.status }}</code>
            <span>{{ action.detail }}</span>
          </li>
        </ul>
        <small v-if="chainRecovery.needsRealRequestVerification">
          {{ t('chainHealth.recoveryNeedsRequest') }}
        </small>
      </div>

      <div v-if="chainHealth?.recommendations?.length" class="chain-health__recommendations">
        <strong>{{ t('chainHealth.recommendations') }}</strong>
        <ol>
          <li v-for="item in chainHealth.recommendations" :key="item">{{ item }}</li>
        </ol>
      </div>

      <div v-if="chainExpanded && chainHealth" class="chain-health__detail">
        <div class="chain-health__facts">
          <div>
            <strong>{{ t('chainHealth.attribution') }}</strong>
            <code>code={{ chainHealth.diagnosis.code }}</code>
            <code v-for="fact in chainHealth.diagnosis.facts" :key="`diagnosis-${fact}`">{{ fact }}</code>
          </div>
          <div v-for="layer in chainLayers" :key="`${layer.key}-facts`">
            <strong>{{ layer.label }}</strong>
            <code v-for="fact in layer.data.facts" :key="fact">{{ fact }}</code>
          </div>
        </div>
        <div v-if="chainHealth.runtime.containers.length" class="chain-health__containers">
          <strong>{{ t('chainHealth.containers') }}</strong>
          <div
            v-for="container in chainHealth.runtime.containers"
            :key="container.id"
            class="chain-container"
            :class="{ 'is-target': container.target }"
          >
            <span>{{ container.service || container.name }}</span>
            <span>{{ container.health || container.status }}</span>
            <span v-if="container.cpu">{{ container.cpu }}</span>
            <span v-if="container.memory">{{ container.memory }}</span>
            <span v-if="container.restartCount">restart {{ container.restartCount }}</span>
            <span v-if="container.restartDelta">recent +{{ container.restartDelta }}</span>
            <span v-if="container.oomKilled">OOM</span>
          </div>
        </div>
        <div class="chain-health__privacy">
          <strong>{{ t('chainHealth.privacy') }}</strong>
          <span v-for="item in chainHealth.privacy" :key="item">{{ item }}</span>
        </div>
      </div>
    </section>

    <!-- ③ 日志面板(标题行 + 分列) -->
    <div class="log-panel">
      <div class="log-panel__head">
        <button class="log-btn" @click="onViewLogs">
          <IconFolder class="log-btn__icon" />
          <span>{{ t('proxy.viewLog') }}</span>
        </button>
        <button class="log-btn" @click="onClearLogs">
          <IconTrash class="log-btn__icon" />
          <span>{{ t('proxy.clearLog') }}</span>
        </button>
        <label class="autoscroll">
          <span>{{ t('proxy.autoScroll') }}</span>
          <AppSwitch v-model="autoScroll" />
        </label>
      </div>
      <div ref="logsEl" class="log-body">
        <div v-if="!store.logs.length" class="log-empty">暂无日志</div>
        <div v-for="(l, i) in store.logs" :key="i" class="log-row">
          <span class="log-time">{{ l.at }}</span>
          <span class="log-level" :class="`log-level--${l.level}`">{{ (l.level || '').toUpperCase() }}</span>
          <span class="log-msg">{{ l.message }}</span>
        </div>
      </div>
    </div>

    <!-- [MOC-261 一-11] 静默丢弃工具诊断(金丝雀):未知 Responses API 工具类型累计 drop 数 -->
    <div class="dropped">
      <template v-if="dropped.total > 0">
        <button type="button" class="dropped__head" @click="droppedExpanded = !droppedExpanded">
          <span class="dropped__title">⚠ {{ t('diagnostic.droppedToolsTitle') }}</span>
          <span class="dropped__count">
            {{ dropped.total }} {{ t('diagnostic.droppedToolsCalls') }} ·
            {{ droppedEntries.length }} {{ t('diagnostic.droppedToolsTypes') }}
          </span>
          <span class="dropped__toggle">{{ t('diagnostic.droppedToolsExpand') }}</span>
        </button>
        <div v-if="droppedExpanded" class="dropped__detail">
          <p class="dropped__hint">{{ t('diagnostic.droppedToolsHint') }}</p>
          <ul class="dropped__list">
            <li v-for="[type, n] in droppedEntries" :key="type">
              <code>{{ type }}</code>
              <span>{{ n }} {{ t('diagnostic.droppedToolsCalls') }}</span>
            </li>
          </ul>
        </div>
      </template>
      <div v-else class="dropped__none">{{ t('diagnostic.droppedToolsNone') }}</div>
    </div>
  </div>
</template>

<style scoped>
.proxy {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

/* [MOC-261 一-11] 静默丢弃工具诊断 */
.dropped {
  font-size: var(--fs-sm);
}
.dropped__none {
  color: var(--text-muted);
  font-size: var(--fs-xs);
}
.dropped__head {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  width: 100%;
  padding: var(--space-2) var(--space-3);
  border: 1px solid var(--warning-soft, rgba(245, 158, 11, 0.4));
  border-radius: var(--radius);
  background: var(--warning-soft, rgba(245, 158, 11, 0.08));
  color: var(--text);
  text-align: left;
  cursor: pointer;
}
.dropped__title {
  font-weight: 600;
}
.dropped__count {
  color: var(--text-secondary);
}
.dropped__toggle {
  margin-left: auto;
  color: var(--accent);
  font-size: var(--fs-xs);
}
.dropped__detail {
  margin-top: var(--space-2);
  padding: var(--space-3);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface-2);
}
.dropped__hint {
  margin: 0 0 var(--space-2);
  color: var(--text-secondary);
  line-height: 1.5;
}
.dropped__list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.dropped__list li {
  display: flex;
  justify-content: space-between;
  gap: var(--space-3);
}
.dropped__list code {
  font-family: var(--font-mono);
}

/* ① 状态条 */
.status-card {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
  padding: var(--space-4) var(--space-5);
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
}
.status-card__left {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}
.pulse {
  width: 12px;
  height: 12px;
  border-radius: var(--radius-full);
  background: var(--text-muted);
  flex-shrink: 0;
}
.pulse--on {
  background: var(--success);
  box-shadow: 0 0 0 4px var(--success-soft);
}
.status-text {
  font-size: var(--fs-lg);
  font-weight: 600;
  color: var(--text-muted);
}
.status-text--on {
  color: var(--success);
}
.status-sub {
  font-size: var(--fs-sm);
  color: var(--text-muted);
}
.status-card__right {
  display: flex;
  align-items: center;
  gap: var(--space-4);
}
.port-field {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}
.port-label {
  font-size: var(--fs-sm);
  color: var(--text-secondary);
  font-weight: 500;
}
.port-input {
  width: 88px;
  height: 32px;
  padding: 0 var(--space-2);
  border: 1px solid var(--border-strong);
  border-radius: var(--radius);
  background: var(--surface);
  color: var(--text);
  font-size: var(--fs-md);
  font-family: var(--font-mono);
}
.port-input:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-soft);
}
.proxy-toggle {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  height: 34px;
  padding: 0 var(--space-4);
  border: none;
  border-radius: var(--radius);
  font-size: var(--fs-md);
  font-weight: 600;
  color: #fff;
}
.proxy-toggle__icon {
  width: 15px;
  height: 15px;
}
.proxy-toggle.is-stop {
  background: var(--danger);
}
.proxy-toggle.is-start {
  background: var(--success);
}

/* ② 四列统计 */
.stat-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--space-3);
}
.stat-card {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-4);
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
}
.stat-card__icon {
  display: grid;
  place-items: center;
  width: 34px;
  height: 34px;
  border-radius: var(--radius-full);
  background: var(--accent-soft);
  color: var(--accent);
  flex-shrink: 0;
}
.stat-card__icon :deep(svg) {
  width: 17px;
  height: 17px;
}
.stat-card__icon--ok {
  background: var(--success-soft);
  color: var(--success);
}
.stat-card__icon--err {
  background: var(--danger-soft);
  color: var(--danger);
}
.stat-card__value {
  font-size: var(--fs-lg);
  font-weight: 700;
  color: var(--text);
  font-variant-numeric: tabular-nums;
}
.stat-card__label {
  font-size: var(--fs-sm);
  color: var(--text-muted);
  white-space: nowrap;
}

/* ③ 暗色日志面板 */
.log-panel {
  background: #11151f;
  border: 1px solid #232a3a;
  border-radius: var(--radius-lg);
  overflow: hidden;
}
.log-panel__head {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: var(--space-3);
  padding: var(--space-3) var(--space-4);
  border-bottom: 1px solid rgba(255, 255, 255, 0.07);
}
.log-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 30px;
  padding: 0 var(--space-3);
  border: 1px solid rgba(255, 255, 255, 0.18);
  border-radius: var(--radius);
  background: transparent;
  color: #c8cdd8;
  font-size: var(--fs-sm);
}
.log-btn:hover {
  background: rgba(255, 255, 255, 0.06);
}
.log-btn__icon {
  width: 14px;
  height: 14px;
}
.autoscroll {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  color: #c8cdd8;
  font-size: var(--fs-sm);
}
.log-body {
  max-height: 380px;
  overflow-y: auto;
  padding: var(--space-3) var(--space-4);
  font-family: var(--font-mono);
  font-size: var(--fs-sm);
  line-height: 1.7;
}
.log-empty {
  color: #6b7280;
  text-align: center;
  padding: var(--space-5) 0;
}
.log-row {
  display: grid;
  grid-template-columns: 72px 70px 1fr;
  gap: var(--space-3);
  white-space: pre-wrap;
  word-break: break-all;
}
.log-time {
  color: #6b7280;
}
.log-level {
  color: #5b9bd5;
  font-weight: 600;
  white-space: nowrap;
}
.log-level--success {
  color: #3fb950;
}
.log-level--warn {
  color: #e0a020;
}
.log-level--error {
  color: #ff6b6b;
}
.log-msg {
  color: #d8dce4;
}

/* CAS-R33-CHAIN-HEALTH */
.chain-health {
  padding: var(--space-4);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  background: var(--surface);
}
.chain-health--error { border-color: color-mix(in srgb, var(--danger) 45%, var(--border)); }
.chain-health--degraded { border-color: color-mix(in srgb, #f59e0b 45%, var(--border)); }
.chain-health__head,
.chain-health__title-row,
.chain-health__actions,
.chain-layer__head,
.chain-container {
  display: flex;
  align-items: center;
}
.chain-health__head { justify-content: space-between; gap: var(--space-4); }
.chain-health__title-row { gap: var(--space-2); }
.chain-health__title-row h2 { margin: 0; font-size: var(--fs-lg); }
.chain-health__pulse,
.chain-layer__dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--text-muted);
  flex: 0 0 auto;
}
.chain-health--ok .chain-health__pulse,
.chain-layer--ok .chain-layer__dot { background: var(--success); }
.chain-health--error .chain-health__pulse,
.chain-layer--error .chain-layer__dot { background: var(--danger); }
.chain-health--degraded .chain-health__pulse,
.chain-layer--degraded .chain-layer__dot { background: #f59e0b; }
.chain-health__overall {
  padding: 2px 8px;
  border-radius: var(--radius-full);
  background: var(--surface-2);
  color: var(--text-secondary);
  font-size: var(--fs-xs);
}
.chain-health__summary,
.chain-health__provider { margin: 5px 0 0; color: var(--text-secondary); }
.chain-health__provider { font-family: var(--font-mono); font-size: var(--fs-xs); word-break: break-all; }
.chain-health__actions { gap: var(--space-2); }
.chain-health__button {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  min-height: 32px;
  padding: 0 var(--space-3);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface-2);
  color: var(--text);
  cursor: pointer;
}
.chain-health__button svg { width: 15px; height: 15px; transition: transform .18s ease; }
.chain-health__button svg.is-open { transform: rotate(180deg); }
.chain-health__button svg.is-spinning { animation: chain-spin .8s linear infinite; }
@keyframes chain-spin { to { transform: rotate(360deg); } }
.chain-health__grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: var(--space-2);
  margin-top: var(--space-4);
}
.chain-layer {
  min-width: 0;
  padding: var(--space-3);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface-2);
}
.chain-layer__head { gap: 6px; }
.chain-layer__head strong { min-width: 0; flex: 1; }
.chain-layer__head span:last-child { color: var(--text-muted); font-size: var(--fs-xs); }
.chain-layer p { min-height: 38px; margin: 8px 0 0; color: var(--text-secondary); font-size: var(--fs-xs); line-height: 1.45; }
.chain-layer small { color: var(--text-muted); font-family: var(--font-mono); }
.chain-health__recommendations {
  margin-top: var(--space-3);
  padding: var(--space-3);
  border-radius: var(--radius);
  background: var(--surface-2);
}
.chain-health__recommendations ol { margin: 7px 0 0 20px; padding: 0; color: var(--text-secondary); }
.chain-health__recommendations li + li { margin-top: 5px; }
.chain-health__detail {
  display: grid;
  gap: var(--space-3);
  margin-top: var(--space-3);
  padding-top: var(--space-3);
  border-top: 1px solid var(--border);
}
.chain-health__facts { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: var(--space-3); }
.chain-health__facts > div,
.chain-health__privacy { display: flex; flex-direction: column; gap: 5px; }
.chain-health__facts code {
  padding: 5px 7px;
  border-radius: 5px;
  background: var(--surface-2);
  color: var(--text-secondary);
  white-space: normal;
  word-break: break-word;
}
.chain-health__containers { display: grid; gap: 6px; }
.chain-container {
  gap: var(--space-3);
  padding: 7px 9px;
  border: 1px solid var(--border);
  border-radius: 6px;
  color: var(--text-secondary);
  font-family: var(--font-mono);
  font-size: var(--fs-xs);
}
.chain-container.is-target { border-color: var(--accent); }
.chain-container span:first-child { flex: 1; color: var(--text); }
.chain-health__privacy { color: var(--text-muted); font-size: var(--fs-xs); }
@media (max-width: 980px) {
  .chain-health__grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  .chain-health__head { align-items: flex-start; flex-direction: column; }
}


.chain-health__recovery-report {
  display: flex;
  flex-direction: column;
  gap: 6px;
  margin-top: 12px;
  padding: 12px;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  background: var(--surface-soft, rgba(127, 127, 127, 0.06));
  font-size: var(--fs-sm);
}
.chain-health__recovery-report ul {
  margin: 0;
  padding-left: 18px;
}
.chain-health__recovery-report li {
  margin: 4px 0;
}
.chain-health__recovery-report code {
  margin-right: 8px;
}
</style>
